name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      - name: 'Set up Java 8'
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Maven version
        run: mvn --version
      - name: Configure Git User
        run: |
          git config user.email "${GITHUB_ACTOR}"
          git config user.name "GitHub Actions"
      - name: Maven Release
        run: mvn --batch-mode release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
